# Generated by Django 4.2.4 on 2023-08-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ключ верификации'),
        ),
    ]
