# Generated by Django 4.2.4 on 2023-08-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verify',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
    ]
