# Generated by Django 4.2.5 on 2023-09-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('comment', models.TextField(verbose_name='коментарии')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(verbose_name='тема')),
                ('description', models.TextField(verbose_name='сообщение')),
                ('mailing_time', models.TimeField(blank=True, null=True, verbose_name='время рассылки')),
                ('mailing_date', models.DateField(blank=True, null=True, verbose_name='дата рассылки')),
                ('period', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], max_length=10, verbose_name='период')),
                ('active', models.CharField(choices=[('yes', 'Активна'), ('no', 'Не активна')], max_length=10, verbose_name='статус')),
                ('clients', models.ManyToManyField(related_name='product', to='catalog.client', verbose_name='клиенты')),
            ],
            options={
                'verbose_name': 'Расслыка',
            },
        ),
    ]
