# Generated by Django 4.2.5 on 2023-09-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='email_adress',
        ),
        migrations.AddField(
            model_name='product',
            name='email_adress',
            field=models.ManyToManyField(through='catalog.ProductClient', to='catalog.client', verbose_name='почта'),
        ),
    ]
