# Generated by Django 4.2.4 on 2023-09-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_description_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='topic',
            field=models.TextField(default=1, verbose_name='тема'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Version',
        ),
    ]
