# Generated by Django 4.2.4 on 2023-09-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_product_created_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
