# Generated by Django 4.2.4 on 2023-09-04 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_delete_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='тема')),
                ('text', models.TextField(verbose_name='текст')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='catalog.product', verbose_name='ключ')),
            ],
        ),
    ]
